language: rust

env:
  global:
    - MODULE_NAME=keeper

os: linux
dist: xenial
addons: &linux_addons
  apt:
    packages:
      - pkg-config
      - libssl-dev
      # needed for musl targets
      - musl-tools
      # needed to build deb packages
      - fakeroot

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu
      addons: *linux_addons
    - rust: stable
      os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-musl
      addons: *linux_addons
    - rust: stable
      os: osx
      env: TARGET=x86_64-apple-darwin
    - rust: beta
      os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu
      addons: *linux_addons
    - rust: beta
      os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-musl
      addons: *linux_addons
    - rust: beta
      os: osx
      env: TARGET=x86_64-apple-darwin
    - rust: nightly
      os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu
      addons: *linux_addons
    - rust: nightly
      os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-musl
      addons: *linux_addons
    - rust: nightly
      os: osx
      env: TARGET=x86_64-apple-darwin

before_install:
  - rustup self update
  - cargo install --version=0.1.16 cross

#install:
#  - rustup target add ${TARGET}

before_script:
  - set -e

script:
  - cross build --target ${TARGET} --verbose

after_script:
  - set +e

before_deploy:
  - cargo build --target ${TARGET} --verbose --release
  - cargo test --target ${TARGET} --verbose --release
  - mkdir -p target/executable
  - cp target/${TARGET}/debug/${MODULE_NAME} target/executable/${MODULE_NAME}-${TRAVIS_TAG}-${TARGET}-debug
  - cp target/${TARGET}/release/${MODULE_NAME} target/executable/${MODULE_NAME}-${TRAVIS_TAG}-${TARGET}

deploy:
  provider: releases
  edge: true
  token: ${GITHUB_CRAWLIS_CI_RELEASE_TOKEN}
  file_glob: true
  file: target/executable/*
  on:
    repo: crawlis/${MODULE_NAME}
    tags: true
    condition: ${TRAVIS_RUST_VERSION} = stable

branches:
  only:
    - master
    # Regex pattern to match tags
    - /^v\d+\.\d+\.\d+.*$/
